name: adf
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  gap: ^3.0.1
  provider: ^6.1.2
  file_picker: ^9.2.1
  carousel_slider: ^5.0.0
  dotted_border: ^2.1.0
  cloudinary_public: ^0.23.1
  shared_preferences: ^2.5.2
  page_transition: ^2.2.1
  flutter_displaymode: ^0.6.0
  font_awesome_flutter: ^10.8.0
  razorpay_flutter: ^1.4.0
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.4
  equatable: ^2.0.7
  google_fonts: ^6.2.1
  imageview360: ^1.3.0
  flutter_3d_controller: ^2.1.0
  model_viewer_plus: ^1.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon1.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon1.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
#  windows:
#    generate: true
#    image_path: "path/to/image.png"
#    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon1.png"
flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/
     - assets/icon/
     - assets/arvabil_sofa/
     - assets/arvabil_swings/
     - assets/arvabil_chairs/
     - assets/arvabil_tables/
     - assets/3d_models/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
